---
# tasks file for nginx

- debug:
    var: hostvars[inventory_hostname]

- name: NGINX | Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: NGINX Plus | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: NGINX | Updating apt cache
  apt:
    update_cache: yes

- name: NGINX | Installing NGINX
  apt: pkg=nginx state=installed update_cache=true

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started

- name: Show ip on landing page
  replace: dest='/usr/share/nginx/html/index.html'
    regexp='<h1>Welcome to nginx!</h1>'
    replace='<h1>Welcome to {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}</h1>'

- name: NGINX | Restart NGINX
  service:
    name: nginx
    state: restarted